import { FastifyInstance } from "fastify";

/**
 * @file Defines the core types for the declarative, tool-based workflow engine.
 * This file is the foundation of our autonomous AI architecture.
 */

/**
 * Describes a single, executable unit of work (a "Tool").
 * Tools are the fundamental building blocks of any workflow.
 * They are designed to be stateless, reusable, and self-describing.
 */
export interface Tool {
  /**
   * A unique identifier for the tool, e.g., "run_shell_command".
   * This is used by the AI planner to reference the tool in a Plan.
   */
  name: string;

  /**
   * A clear, concise description of what the tool does.
   * The AI uses this to understand the tool's purpose and decide when to use it.
   */
  description: string;

  /**
   * A JSON schema defining the expected input parameters for the tool.
   * This allows for validation and provides a clear contract for the AI.
   */
  inputSchema: Record<string, any>; // More specific JSON schema type can be used here

  /**
   * A JSON schema defining the shape of the tool's output.
   */
  outputSchema: Record<string, any>;

  /**
   * The actual implementation of the tool.
   * @param context - The execution context, providing access to shared resources like loggers.
   * @param input - The input parameters, validated against `inputSchema`.
   * @returns A promise that resolves with the tool's output.
   */
  execute(context: ExecutionContext, input: any): Promise<any>;
}

/**
 * Retry policy configuration for a step
 */
export interface RetryPolicy {
  /**
   * Maximum number of retry attempts
   */
  maxRetries: number;

  /**
   * Backoff strategy: 'linear', 'exponential', or 'fixed'
   */
  backoff: "linear" | "exponential" | "fixed";

  /**
   * Initial delay in milliseconds
   */
  initialDelay?: number;

  /**
   * Maximum delay in milliseconds
   */
  maxDelay?: number;
}

/**
 * Represents a single step within a workflow Plan.
 * Each step executes a specific Tool with defined inputs.
 */
export interface PlanStep {
  /**
   * A unique identifier for this step within the plan, e.g., "analyzeRequirementsStep".
   */
  id: string;

  /**
   * A user-friendly title for this step, e.g., "Setting up the project".
   * This is generated by the AI for display in the UI.
   */
  title: string;

  /**
   * A user-friendly description of what this step does.
   * This is also generated by the AI for the UI.
   */
  description: string;

  /**
   * The name of the Tool to execute for this step. Must match a registered tool's name.
   */
  tool: string;

  /**
   * The input parameters for the tool.
   * This can contain static values or dynamic references to outputs of previous steps.
   * e.g., { "projectPath": "${steps.setupProjectStep.outputs.path}" }
   */
  inputs: Record<string, any>;

  /**
   * An array of step IDs that must be completed before this step can start.
   * This defines the DAG structure of the workflow.
   */
  dependencies?: string[];

  /**
   * Optional condition for step execution
   * e.g., "${steps.previousStep.outputs.success} === true"
   */
  conditional?: string;

  /**
   * Retry policy for this step
   */
  retryPolicy?: RetryPolicy;

  /**
   * Optional rollback action step ID
   */
  rollbackAction?: string;

  /**
   * Estimated execution time in milliseconds
   */
  estimatedDuration?: number;

  /**
   * Priority level for execution (higher = more priority)
   */
  priority?: number;
}

/**
 * Represents the entire workflow to be executed.
 * This is the "Plan" generated by the AI planner.
 */
export interface Plan {
  /**
   * A descriptive name for the workflow.
   */
  name: string;

  /**
   * A brief explanation of the workflow's overall goal.
   */
  description: string;

  /**
   * The sequence of steps that make up the workflow.
   */
  steps: PlanStep[];

  /**
   * Estimated total execution time
   */
  estimatedDuration?: string;

  /**
   * Whether the plan can be parallelized
   */
  parallelizable?: boolean;

  /**
   * Plan metadata
   */
  metadata?: {
    version: string;
    createdAt: string;
    complexity: "simple" | "medium" | "complex";
    tags: string[];
  };
}

/**
 * The context passed to each tool during execution.
 * It provides access to shared, request-scoped resources.
 */
export interface ExecutionContext {
  // A logger instance for structured logging.
  // logger: Logger;

  // A unique ID for the entire workflow execution run.
  runId: string;

  // The Fastify application instance
  app: FastifyInstance;

  // Potentially, access to other services or configuration.
  // Optional contextual identifiers for tools that require project/user scope
  projectId?: string;
  userId?: string;
}
